let bearer = "";
let csrf = "";
const headers = {};
async function controlPlaneLogin(token) {
  if (!token) return false;
  const response = await fetch("/api/auth/session", { method: "POST", credentials: "same-origin", headers: { Authorization: `Bearer ${token}` } });
  if (!response.ok) return false;
  const result = await response.json(); csrf = result.csrfToken || ""; bearer = ""; return true;
}
window.controlPlaneLogin = controlPlaneLogin;
async function ensureSession() { if (csrf) return true; const token = prompt("Token del panel"); return controlPlaneLogin(token); }
let lastLive = 0;
let consoleEpoch = null;
const $ = id => document.getElementById(id);
document.querySelectorAll("[data-screen]").forEach(button => button.onclick = () => { const id = button.dataset.screen; document.querySelectorAll(".screen").forEach(screen => screen.classList.toggle("active", screen.id === id)); document.querySelectorAll("[data-screen]").forEach(item => item.classList.toggle("active", item.dataset.screen === id)); window.scrollTo({ top: 0, behavior: "smooth" }); });
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
const inspector = { enabled: false, selected: null, reports: JSON.parse(localStorage.getItem("redmi-ui-issues") || "[]") };
const inspectorSafeText = value => String(value ?? "").replace(/[\r\n\t]+/g, " ").replace(/\s+/g, " ").trim().slice(0, 500);
function downloadReports() {
  if (!inspector.reports.length) return;
  const body = inspector.reports.map(report => JSON.stringify(report)).join("\n") + "\n";
  const url = URL.createObjectURL(new Blob([body], { type: "application/x-ndjson" }));
  const link = document.createElement("a"); link.href = url; link.download = `ui-issues-${new Date().toISOString().slice(0, 10)}.jsonl`; link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function closeInspector() { document.getElementById("inspectorPanel")?.remove(); document.querySelectorAll(".inspector-selected").forEach(node => node.classList.remove("inspector-selected")); inspector.selected = null; }
function openInspector(target) {
  closeInspector(); inspector.selected = target; target.classList.add("inspector-selected");
  const rect = target.getBoundingClientRect();
  const panel = document.createElement("form"); panel.id = "inspectorPanel"; panel.className = "inspector-panel";
  panel.innerHTML = `<strong>Beta Inspector</strong><span>${escapeHtml(target.dataset.inspectorId || target.id || target.tagName.toLowerCase())}</span><select name="issueType"><option value="layout">Layout</option><option value="text">Texto</option><option value="image">Imagen</option><option value="behavior">Comportamiento</option></select><textarea name="description" required maxlength="500" placeholder="Describe el problema"></textarea><div class="inspector-actions"><button type="button" class="button secondary" data-inspector-clear>Limpiar</button><button type="button" class="button secondary" data-inspector-close>Cerrar</button><button class="button" type="submit">Guardar JSONL</button></div>`;
  document.body.append(panel); panel.style.left = `${Math.min(Math.max(12, rect.left), window.innerWidth - 332)}px`; panel.style.top = `${Math.min(rect.bottom + 10, window.innerHeight - 230)}px`;
  panel.querySelector("[data-inspector-close]").onclick = closeInspector;
  panel.querySelector("[data-inspector-clear]").onclick = () => { inspector.reports = []; localStorage.removeItem("redmi-ui-issues"); closeInspector(); };
  panel.onsubmit = event => { event.preventDefault(); const form = new FormData(panel); inspector.reports.push({ timestamp: new Date().toISOString(), screen: location.pathname, elementId: inspectorSafeText(target.dataset.inspectorId || target.id || target.tagName.toLowerCase()), issueType: form.get("issueType"), description: inspectorSafeText(form.get("description")), screenshotFile: null, metadata: { userAgent: navigator.userAgent.slice(0, 160) } }); localStorage.setItem("redmi-ui-issues", JSON.stringify(inspector.reports)); downloadReports(); closeInspector(); };
}
function initInspector() {
  $("inspectorToggle").onclick = () => { inspector.enabled = !inspector.enabled; $("inspectorToggle").setAttribute("aria-pressed", String(inspector.enabled)); $("inspectorToggle").textContent = inspector.enabled ? "Salir del inspector" : "Inspector beta"; if (!inspector.enabled) closeInspector(); };
  document.addEventListener("click", event => { if (!inspector.enabled || event.target.closest("#inspectorPanel, #inspectorToggle")) return; const target = event.target.closest("[data-inspectable=\"true\"]"); if (target) { event.preventDefault(); event.stopPropagation(); openInspector(target); } }, true);
}
const statusClass = value => ["online", "offline", "starting", "error"].includes(value) ? value : "unknown";
async function api(path, options = {}) { const requestHeaders = { ...headers, ...(options.headers || {}) }; if (csrf && options.method && options.method !== "GET") requestHeaders["x-csrf-token"] = csrf; if (bearer) requestHeaders.Authorization = `Bearer ${bearer}`; const response = await fetch(path, { ...options, credentials: "same-origin", headers: requestHeaders }); if (!response.ok) { let detail = `${response.status}`; try { const body = await response.json(); detail = body.error || detail; } catch {} throw new Error(detail); } return response.status === 204 ? null : response.json(); }
function setConnection(ok) { $("connectionDot").parentElement.classList.toggle("online", ok); $("connectionText").textContent = ok ? "Conectado" : "Desconectado"; }
function statusLabel(s) { return s === "online" ? "Online" : s === "starting" ? "Iniciando" : s === "offline" ? "Offline" : "Desconocido"; }
async function refresh() { try { const [device, profiles, services, audit, apps] = await Promise.all([api("/api/stats/live"), api("/api/profiles"), api("/api/services"), api("/api/audit"), api("/api/apps")]); renderDevice(device); renderProfiles(profiles); renderServices(services.data); renderApps(apps.data); renderAudit(audit.data); api("/api/access/devices").then(result => renderDevices(result.data)).catch(() => renderDevices(null)); lastLive = Date.now(); setConnection(true); } catch (e) { if (!lastLive || Date.now() - lastLive > 10000) setConnection(false); console.error(e); } }
function renderDevice(d) { const lan = d.network?.lan?.ip; const tailscale = d.network?.tailscale?.ip; const host = d.minecraft.host; $("activeProfile").textContent = d.profile; $("ram").textContent = `${d.ram.available} MB`; $("zram").textContent = `zRAM ${d.ram.zramUsed} MB`; $("cpu").textContent = d.cpu.usage ? `${d.cpu.usage}%` : "n/d"; $("temp").textContent = d.cpu.temperature ? `${d.cpu.temperature} °C` : "Temperatura no disponible"; $("mcState").textContent = statusLabel(d.minecraft.status); $("mcAddress").textContent = `${host}:${d.minecraft.port}`; $("root").textContent = d.rootControl ? "Activo" : "Protegido"; $("updated").textContent = new Date(d.at).toLocaleTimeString(); $("minecraftBadge").textContent = statusLabel(d.minecraft.status); $("minecraftBadge").className = `badge ${d.minecraft.status}`; $("serverAddress").textContent = `${host}:${d.minecraft.port}`; $("serverAddressSource").textContent = `Detectada por ${d.minecraft.hostSource || "configuración"}`; $("paperVersion").textContent = d.minecraft.version ? `Paper: ${d.minecraft.version}` : "Paper: versión no disponible"; $("localPanelAddress").textContent = lan ? `http://${lan}:3000` : "No detectada"; $("tailscalePanelAddress").textContent = tailscale ? `http://${tailscale}:3000` : "No detectada"; $("craftyAddress").textContent = `https://${tailscale || lan || host}:8443`; if (consoleEpoch !== d.minecraft.consoleEpoch) { consoleEpoch = d.minecraft.consoleEpoch; $("log").textContent = "Nueva sesión: esperando salida de Paper..."; } if (d.minecraft.logTail) $("log").textContent = d.minecraft.logTail; else if (d.minecraft.status === "offline") $("log").textContent = "Servidor detenido. La consola se limpiará en el próximo arranque."; }
function renderProfiles(result) { $("profilesList").innerHTML = result.data.map(p => `<div class="profile ${p.id === result.active ? "active" : ""}"><div><div class="profile-name">${escapeHtml(p.name)}</div><div class="profile-desc">${escapeHtml(p.description)}</div></div><button class="button secondary" data-profile="${escapeHtml(p.id)}">${p.id === result.active ? "Activo" : "Activar"}</button></div>`).join(""); document.querySelectorAll("[data-profile]").forEach(b => b.onclick = async () => { const target = result.data.find(p => p.id === b.dataset.profile); if (result.active === "minecraft" && target?.id === "normal" && !window.confirm("Se detendrán Minecraft y Crafty de forma segura; después se restaurarán las aplicaciones. ¿Continuar?")) return; try { await api(`/api/profiles/${encodeURIComponent(b.dataset.profile)}/activate`, { method: "POST" }); refresh(); } catch (error) { window.alert(`No se pudo cambiar el perfil: ${error.message}`); } }); }
function renderServices(items) { $("servicesList").innerHTML = items.map(s => `<div class="service" data-inspectable="true" data-inspector-id="service:${escapeHtml(s.name)}"><div><div class="service-name">${escapeHtml(s.name)}</div><div class="service-meta">${escapeHtml(s.detail || (s.port ? `Puerto ${s.port}` : "Servicio local"))}</div></div><span class="status ${statusClass(s.status)}">${s.status === "error" ? "Error" : statusLabel(s.status)}</span></div>`).join(""); }
function renderApps(items) { $("appsList").innerHTML = items.map(a => `<div class="service"><div><div class="service-name">${escapeHtml(a.name)}</div><div class="service-meta">${escapeHtml(a.package)}</div></div><span class="status ${statusClass(a.status)}">${a.status === "protected" ? "Protegida" : "Disponible"}</span></div>`).join(""); }
function renderAudit(items = []) { $("audit").innerHTML = items.slice(0, 40).map(x => `<div class="audit"><time>${escapeHtml(new Date(x.at).toLocaleString())}</time><strong>${escapeHtml(x.action)}</strong><br><span>${escapeHtml(JSON.stringify(x.detail))}</span></div>`).join("") || '<div class="empty">Sin actividad todavía.</div>'; }
function renderDevices(items) { const list = $("devicesList"); if (!items) { list.innerHTML = '<div class="empty">La gestión de dispositivos requiere rol propietario.</div>'; $("deviceForm").hidden = true; return; } $("deviceForm").hidden = false; list.innerHTML = items.map(d => `<div class="service"><div><div class="service-name">${escapeHtml(d.name)}</div><div class="service-meta">${escapeHtml(d.role)}${d.allowedIp ? ` · ${escapeHtml(d.allowedIp)}` : " · cualquier IP de la tailnet"}</div></div><button class="button secondary" data-revoke="${escapeHtml(d.id)}" ${d.revoked ? "disabled" : ""}>${d.revoked ? "Revocado" : "Revocar"}</button></div>`).join("") || '<div class="empty">No hay dispositivos adicionales.</div>'; document.querySelectorAll("[data-revoke]").forEach(button => button.onclick = async () => { if (!confirm("Este dispositivo perderá el acceso inmediatamente. ¿Continuar?")) return; await api(`/api/access/devices/${encodeURIComponent(button.dataset.revoke)}`, { method: "DELETE" }); refresh(); }); }
$("refresh").onclick = refresh; $("restoreButton").onclick = async () => { await api("/api/profiles/restore", { method: "POST" }); refresh(); }; $("copyAddress").onclick = () => navigator.clipboard.writeText($("serverAddress").textContent); const sendMinecraftCommand = async () => { const input = $("commandInput"); const command = input.value.trim(); if (!command) return; const button = $("sendCommand"); button.disabled = true; try { await api("/api/minecraft/command", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command }) }); input.value = ""; refresh(); } catch (error) { window.alert(`Comando no enviado: ${error.message}`); } finally { button.disabled = false; } }; $("sendCommand").onclick = sendMinecraftCommand; $("commandInput").addEventListener("keydown", event => { if (event.key === "Enter") sendMinecraftCommand(); });
document.querySelectorAll(".copy-access").forEach(button => button.onclick = async () => { const value = $(button.dataset.copyTarget)?.textContent || ""; if (!value || /Calculando|No detectada/.test(value)) return; await navigator.clipboard.writeText(value); button.textContent = "Copiado"; setTimeout(() => { button.textContent = "Copiar"; }, 1200); });
$("deviceForm").onsubmit = async event => { event.preventDefault(); const result = await api("/api/access/devices", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: $("deviceName").value, role: $("deviceRole").value, allowedIp: $("deviceIp").value.trim() || null }) }); const box = $("issuedToken"); box.hidden = false; box.textContent = `Token (se muestra una sola vez): ${result.token}`; $("deviceName").value = ""; refresh(); };
async function streamEvents() { while (true) { try { const response = await fetch("/api/events", { headers }); if (!response.ok || !response.body) throw new Error(`events_${response.status}`); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const frames = buffer.split("\n\n"); buffer = frames.pop() || ""; for (const frame of frames) { const type = frame.match(/^event:\s*(.+)$/m)?.[1]; const data = frame.match(/^data:\s*(.+)$/m)?.[1]; if (type === "device.stats" && data) { renderDevice(JSON.parse(data)); lastLive = Date.now(); setConnection(true); } } } } catch (error) { if (!lastLive || Date.now() - lastLive > 10000) setConnection(false); await new Promise(resolve => setTimeout(resolve, 3000)); } } }
initInspector(); ensureSession().then(ok => { if (ok) { refresh(); streamEvents(); setInterval(refresh, 10000); } else setConnection(false); });
